{% set name = "tzinfo" %}
{% set version = "2.0.4" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 9fd0906c2409f729e90c78695e1001fa28f2fa72faa5ad2f6074c3e44e2f1783

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-thread_safe >=0.1,<1
    - rb-concurrent-ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: TZInfo provides access to time zone data and allows times to be converted using time zone rules.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/tzinfo/{{ name }}

extra:
  recipe-maintainers:
    - sodre
