travis:
  secure:
    BINSTAR_TOKEN: HPjvCVZJAKyJ8pdVpXTGaO9mso/3nQSO7vyq3w8HZ5twitXeOB38MIxtFHU2BLxn6L+p3vJcJzrXEzaVKbwDe5eokEKsA86ZtQzPqQF55B432A7lr8b99vvI798iveYp00Ish0hJoLxEgxnzPQHpF8TBb2JpJ2AMBm/DFM/OGfzRft112kPpEjV74BxIO4Kxpkfuch/lOlKIKUjhd37cHRJ3pE+UvtdtTl5vuPovEu1Wif8gu6tHgnolno3i70JKof0I6jtzmgqLeTQKhdedBtA1sphJlfvfH+E4J6oodW34TJmwxKR+VuF/D8B3kZs9yyDdo0kE9wu6fi8ZICXwE9iEoV9cjszmuGANSpzuLp+wvbfOJmu/ycBaVSfrlIP+5xr7d31PhRhVYc3huB8yh66Yl2aSIREWNqUzfPw+spuWAy9DSTIuWEQQKOD3MQzEq2E5FOePdYGyw11Cx3s8NkMrlD91NYEoJtpg0IOZRmLtZlcGe/u8I0VWhH+h4XZS6eDOhH6/33p3cDB1BHVMBNeiWk+gzyZBhU4ESN/TtFLJFTK9/eao0PkHMHJqsr1p4M2RYzoo9veL53qjtrytTTjanCTa07Isqkk4pCsTdjKgd5L0syOyExzIQiaZkriF1TQLYyEhIQB8N/ZxiUnrQiGnaEJepdQQeT7SVypr8Tk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
